server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "lospibesowo"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: false
      http: true
      local: false
    bufferDurationMs: 4000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    searchEnabled: true
    soundcloudSearchEnabled: true

logging:
  level:
    root: INFO