[build]
builder = "nixpacks"

[build.nixpacksConfig]
providers = ["nodejs", "python"]

[build.nixpacksConfig.variables]
NPM_CONFIG_PRODUCTION = "false"

[build.nixpacksConfig.phases.install]
cmds = ["npm install", "pip install yt-dlp"]